export default defineI18nConfig(() => ({
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en: {
      appName: 'Raccoon Gear Bin', tagLine: 'Premium gaming gear for serious players', catalog: 'Catalog', all: 'All categories', controllers: 'Controllers', keyboards: 'Keyboards', mice: 'Mice', headphones: 'Headphones', earphones: 'Earphones', featured: 'Featured gear', inStock: 'In Stock', lowStock: 'Low Stock', outOfStock: 'Out of Stock', viewDetails: 'View details', explore: 'Explore the collection', language: 'Language', shopByCategory: 'Shop by category', specs: 'Specifications', price: 'Price', stock: 'Stock', details: 'Details', noProducts: 'No products match this view.', home: 'Home', products: 'Products', backToProducts: 'Back to products', collection: 'The collection', allProducts: 'All products', searchCatalog: 'Search the catalog', searchProducts: 'Search products', newest: 'Newest', priceLow: 'Price: low to high', priceHigh: 'Price: high to low', nameAZ: 'Name A-Z', noImage: 'No image', adminLogin: 'Admin login', adminMode: 'Admin mode', logout: 'Log out', addProduct: 'Add product', editProduct: 'Edit product', saveChanges: 'Save changes', cancel: 'Cancel', deleteProduct: 'Delete product', close: 'Close', adminAccess: 'Admin access', signIn: 'Sign in', signingIn: 'Signing in...', email: 'Email', password: 'Password', emailPlaceholder: 'admin@example.com', passwordPlaceholder: 'Your password', requiredCategory: 'Choose a category before saving.', invalidLogin: 'Login failed. Please check your credentials.', unauthorized: 'This account is not authorized as an admin.', productSaveError: 'The product could not be saved.', productDeleteError: 'The product could not be deleted.', productLoadError: 'This product could not be loaded.', catalogLoadError: 'The catalog could not be loaded.', productNotFound: 'Product not found', productNotFoundDescription: 'This product may have been removed or is not currently published.', browseProducts: 'Browse products', shortDescription: 'Short description', fullDescription: 'Full description', productName: 'Product name', category: 'Category', sku: 'SKU', slug: 'Slug', imagePaths: 'Product image paths', uploadImages: 'Upload images', specificationsHint: 'JSON or one label: value pair per line', imagePathsHint: 'One public URL or Supabase storage path per line', deleteConfirm: 'Delete {name}?', deleteWarning: 'This removes the product and its translations and images. This action cannot be undone.'
    },
    km: {
      appName: 'រ៉ាកូន ជីហ្គ័រ ប៊ីន', tagLine: 'ឧបករណ៍លេងហ្គេមគុណភាពខ្ពស់សម្រាប់អ្នកលេងពិតប្រាកដ', catalog: 'កាតាឡុក', all: 'គ្រប់ប្រភេទ', controllers: 'ឧបករណ៍បញ្ជា', keyboards: 'ក្ដារចុច', mice: 'កណ្ដុរ', headphones: 'កាសធំ', earphones: 'កាសតូច', featured: 'ឧបករណ៍ពិសេស', inStock: 'មានក្នុងស្តុក', lowStock: 'ស្តុកទាប', outOfStock: 'អស់ពីស្តុក', viewDetails: 'មើលព័ត៌មានលម្អិត', explore: 'ស្វែងរកផលិតផល', language: 'ភាសា', shopByCategory: 'ជ្រើសរើសតាមប្រភេទ', specs: 'លក្ខណៈបច្ចេកទេស', price: 'តម្លៃ', stock: 'ស្តុក', details: 'ព័ត៌មានលម្អិត', noProducts: 'មិនមានផលិតផលដែលត្រូវនឹងការជ្រើសរើសទេ។', home: 'ទំព័រដើម', products: 'ផលិតផល', backToProducts: 'ត្រឡប់ទៅផលិតផល', collection: 'បណ្តុំផលិតផល', allProducts: 'ផលិតផលទាំងអស់', searchCatalog: 'ស្វែងរកក្នុងកាតាឡុក', searchProducts: 'ស្វែងរកផលិតផល', newest: 'ថ្មីបំផុត', priceLow: 'តម្លៃ៖ ទាបទៅខ្ពស់', priceHigh: 'តម្លៃ៖ ខ្ពស់ទៅទាប', nameAZ: 'ឈ្មោះ ក-អ', noImage: 'គ្មានរូបភាព', adminLogin: 'ចូលគ្រប់គ្រង', adminMode: 'របៀបគ្រប់គ្រង', logout: 'ចាកចេញ', addProduct: 'បន្ថែមផលិតផល', editProduct: 'កែសម្រួលផលិតផល', saveChanges: 'រក្សាទុក', cancel: 'បោះបង់', deleteProduct: 'លុបផលិតផល', close: 'បិទ', adminAccess: 'ការចូលគ្រប់គ្រង', signIn: 'ចូលប្រើ', signingIn: 'កំពុងចូល...', email: 'អ៊ីមែល', password: 'ពាក្យសម្ងាត់', emailPlaceholder: 'admin@example.com', passwordPlaceholder: 'ពាក្យសម្ងាត់របស់អ្នក', invalidLogin: 'ការចូលបរាជ័យ។ សូមពិនិត្យអ៊ីមែល និងពាក្យសម្ងាត់។', unauthorized: 'គណនីនេះមិនមានសិទ្ធិជាអ្នកគ្រប់គ្រងទេ។', requiredCategory: 'សូមជ្រើសរើសប្រភេទមុនពេលរក្សាទុក។', productSaveError: 'មិនអាចរក្សាទុកផលិតផលបានទេ។', productDeleteError: 'មិនអាចលុបផលិតផលបានទេ។', productLoadError: 'មិនអាចផ្ទុកផលិតផលនេះបានទេ។', catalogLoadError: 'មិនអាចផ្ទុកកាតាឡុកបានទេ។', productNotFound: 'រកមិនឃើញផលិតផល', productNotFoundDescription: 'ផលិតផលនេះប្រហែលត្រូវបានលុប ឬមិនទាន់ផ្សព្វផ្សាយ។', browseProducts: 'រកមើលផលិតផល', shortDescription: 'ការពិពណ៌នាខ្លី', fullDescription: 'ការពិពណ៌នាពេញលេញ', productName: 'ឈ្មោះផលិតផល', category: 'ប្រភេទ', sku: 'SKU', slug: 'Slug', imagePaths: 'ផ្លូវរូបភាពផលិតផល', uploadImages: 'បញ្ចូលរូបភាព', specificationsHint: 'JSON ឬសរសេរ label: value មួយជួរក្នុងមួយលក្ខណៈ', imagePathsHint: 'URL សាធារណៈ ឬផ្លូវ Supabase មួយក្នុងមួយជួរ', deleteConfirm: 'លុប {name} មែនទេ?', deleteWarning: 'វានឹងលុបផលិតផល ការបកប្រែ និងរូបភាព។ សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។'
    }
  }
}))
